services:
  postgres_customers:
    container_name: postgres_customers
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PG_DAT: admin
    volumes:
      - postgres_customers:/data/postgres_customers
    ports:
      - "5432:5432"
    networks:
      - postgres_customers
    restart: unless-stopped

  postgres_fraud:
    container_name: postgres_fraud
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PG_DAT: admin
    volumes:
      - postgres_fraud:/data/postgres_fraud
    ports:
      - "5332:5432"
    networks:
      - postgres_fraud
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_EMAIL:-pgadmin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres_customers
    restart: unless-stopped

networks:
  postgres_customers:
    driver: bridge
  postgres_fraud:
    driver: bridge


volumes:
  postgres_customers:
  postgres_fraud:
  pgadmin :


