version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: customers
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: shopping_cart
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.2.4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
      - tempo

  tempo:
    container_name: tempo
    image: grafana/tempo:2.4.1   # лучше НЕ latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - "E:/JavaProject/amigosservices/tempo.yaml:/etc/tempo.yaml:ro"
    ports:
      - "3200:3200"
    restart: unless-stopped

  tempo-query:
    container_name: tempo-query
    image: grafana/tempo-query:2.4.1
    environment:
      - BACKEND=tempo:3200
    ports:
      - "16686:16686"
    depends_on:
      - tempo
    restart: unless-stopped
#    image: grafana/tempo-query:2.4.1
#    command:
#      - --grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml
#    volumes:
#      - "E:/JavaProject/amigosservices/tempo-query.yaml:/etc/tempo-query.yaml:ro"
#    ports:
#      - "16686:16686"   # Jaeger UI
#    depends_on:
#      - tempo
#    restart: unless-stopped

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - "E:/JavaProject/amigosservices/otel-collector.yaml:/etc/otel-collector.yaml:ro"
    ports:
      - "4317:4317"     # OTLP gRPC для локальных приложений
      - "4318:4318"     # OTLP HTTP для локальных приложений
    depends_on:
      - tempo
    restart: unless-stopped

#Для контейнеров проекта
  apigw:
    container_name: apigw
    image: zaharchuk90/apigw:1.0-SNAPSHOT
    networks:
      - spring
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8085:8085"

#  fraud:
#    container_name: fraud
#    image: zaharchuk90/fraud:1.0-SNAPSHOT
#    networks:
#      - spring
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    ports:
#      - "8082:8082"



networks:
  postgres:
    driver: bridge
  mysql:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  mysql: