
spring:
  application:
    name: shopping-cart
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_cart?createDatabaseIfNotExist=TRUE&useSSL=false&serverTimezone=UTC
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  jwt:
    secret: fCcaXeHLgdiGTMDJYBjFmiaUScqhMRQrPA2JXBIi2QUpDHh9cCz8ijKy25a1rqqYbKW7hrB67TGNbU2T25aE6lwhPUbjoLmaoZs3ynglag79EM6DVEoOgpDHuKIcKpgWynpr1JoIcb7ggu9hrBhHGemITCxSoz42qFR2o7Ir2pjQ6RxvPsYi4Z9Uank85nYtmtspuWxydjhKsny7Zmhp83RfBd21osFbuKoZjUmzxbgMlNv1ZIbt1WgHlkHGwRfc
    accessTokenExpiration: 300
    refreshTokenExpiration: 604800


app:
  page:
    size: 10
server:
  port: 8084


  #secret: ${JWT_SECRET}


#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics,prometheus
#  tracing:
#    sampling:
#      probability: 1.0
#  otlp:
#    tracing:
#      endpoint: http://localhost:4318/v1/traces
#    metrics:
#      export:
#        enabled: false