name: CD - Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres:15
#        env:
#          POSTGRES_USER: admin
#          POSTGRES_PASSWORD: admin
#          POSTGRES_DB: postgres
#        ports:
#          - 5432:5432
#        options:
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#    defaults:
#      run:
#        working-directory: ./backend

    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}